"""
This type stub file was generated by pyright.
"""

import platform

""":mod:`wand.api` --- Low-level interfaces
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.. versionchanged:: 0.1.10
   Changed to throw :exc:`~exceptions.ImportError` instead of
   :exc:`~exceptions.AttributeError` when the shared library fails to load.

"""
if platform.system() == "Windows":
    ...
__all__ = ('AffineMatrix', 'MagickPixelPacket', 'library', 'libc', 'libmagick', 'load_library', 'PixelInfo', 'PointInfo')
def library_paths(): # -> Generator[tuple[Any, Any] | tuple[str | None, str | None] | tuple[str | None, str], Any, None]:
    """Iterates for library paths to try loading.  The result paths are not
    guaranteed that they exist.

    :returns: a pair of libwand and libmagick paths.  they can be the same.
              path can be ``None`` as well
    :rtype: :class:`tuple`

    """
    ...

def load_library(): # -> tuple[CDLL, CDLL]:
    """Loads the MagickWand library.

    :returns: the MagickWand library and the ImageMagick library
    :rtype: :class:`ctypes.CDLL`

    """
    ...

libraries = ...
library = ...
libmagick = ...
IM_VERSION = ...
IM_QUANTUM_DEPTH = ...
IM_HDRI = ...
libc = ...
if platform.system() == 'Windows':
    msvcrt = ...
else:
    libc_path = ...
