"""
This type stub file was generated by pyright.
"""

""":mod:`wand.assertions` --- Input assertion helpers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module checks user input before calling MagickWands C-API methods.


.. versionadded:: 0.5.4
"""
def assert_bool(**kwargs): # -> None:
    """Ensure all given values are boolean.

    :raises TypeError: if value is not ``True`` or ``False.

    .. versionadded:: 0.5.4
    """
    ...

def assert_color(**kwargs): # -> None:
    """Ensure all given values are instances of :class:`~wand.color.Color`.

    :raises TypeError: if value is not :class:`~wand.color.Color`.

    .. versionadded:: 0.5.4
    """
    ...

def assert_counting_number(**kwargs): # -> None:
    """Ensure all given values are natural integer.

    :raises TypeError: if value is not an integer.
    :raises ValueError: if value is less than ``1``.

    .. versionadded:: 0.5.4
    """
    ...

def assert_integer(**kwargs): # -> None:
    """Ensure all given values are an integer.

    :raises TypeError: if value is not an integer.

    .. versionadded:: 0.5.4
    """
    ...

def assert_real(**kwargs): # -> None:
    """Ensure all given values are real numbers.

    :raises TypeError: if value is not a real number.

    .. versionadded:: 0.5.4
    """
    ...

def assert_unsigned_integer(**kwargs): # -> None:
    """Ensure all given values are positive integer.

    :raises TypeError: if value is not an integer.
    :raises ValueError: if value is less than ``0``.

    .. versionadded:: 0.5.4
    """
    ...

def assert_coordinate(**kwargs): # -> None:
    """Ensure all given values are a sequence of 2 real numbers.

    :raises TypeError: if value is not a pair of doubles.

    .. versionadded:: 0.6.0
    """
    ...

def assert_string(**kwargs): # -> None:
    ...

def in_list(options, label, **kwargs): # -> None:
    ...

def string_in_list(options, label, **kwargs): # -> None:
    ...

