"""
This type stub file was generated by pyright.
"""

import collections
from .resource import Resource

""":mod:`wand.drawing` --- Drawings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The module provides some vector drawing functions.

.. versionadded:: 0.3.0

"""
__all__ = ('CLIP_PATH_UNITS', 'FILL_RULE_TYPES', 'FONT_METRICS_ATTRIBUTES', 'GRAVITY_TYPES', 'LINE_CAP_TYPES', 'LINE_JOIN_TYPES', 'PAINT_METHOD_TYPES', 'STRETCH_TYPES', 'STYLE_TYPES', 'TEXT_ALIGN_TYPES', 'TEXT_DECORATION_TYPES', 'TEXT_DIRECTION_TYPES', 'Drawing', 'FontMetrics')
CLIP_PATH_UNITS = ...
TEXT_ALIGN_TYPES = ...
TEXT_DECORATION_TYPES = ...
TEXT_DIRECTION_TYPES = ...
GRAVITY_TYPES = ...
FILL_RULE_TYPES = ...
FONT_METRICS_ATTRIBUTES = ...
STRETCH_TYPES = ...
STYLE_TYPES = ...
LINE_CAP_TYPES = ...
LINE_JOIN_TYPES = ...
PAINT_METHOD_TYPES = ...
class Drawing(Resource):
    """Drawing object.  It maintains several vector drawing instructions
    and can get drawn into zero or more :class:`~wand.image.Image` objects
    by calling it.

    For example, the following code draws a diagonal line to the ``image``::

        with Drawing() as draw:
            draw.line((0, 0), image.size)
            draw(image)

    :param drawing: an optional drawing object to clone.
                    use :meth:`clone()` method rather than this parameter
    :type drawing: :class:`Drawing`

    .. versionadded:: 0.3.0

    """
    c_is_resource = ...
    c_destroy_resource = ...
    c_get_exception = ...
    c_clear_exception = ...
    def __init__(self, drawing=...) -> None:
        ...
    
    @property
    def border_color(self): # -> Color:
        """(:class:`~wand.color.Color`) the current border color. It also can
        be set. This attribute controls the behavior of
        :meth:`~wand.drawing.Drawing.color()` during ``'filltoborder'``
        operation.

        .. versionadded:: 0.4.0
        """
        ...
    
    @border_color.setter
    def border_color(self, color): # -> None:
        ...
    
    @property
    def clip_path(self): # -> bytes | None:
        """(:class:`basestring`) The current clip path. It also can be set.

        .. versionadded:: 0.4.0

        .. versionchanged: 0.4.1
           Safely release allocated memory with
           :c:func:`MagickRelinquishMemory` instead of :c:func:`libc.free`.

        """
        ...
    
    @clip_path.setter
    def clip_path(self, path): # -> None:
        ...
    
    @property
    def clip_rule(self):
        """(:class:`basestring`) The current clip rule. It also can be set.
        It's a string value from :const:`FILL_RULE_TYPES` list.

        .. versionadded:: 0.4.0
        """
        ...
    
    @clip_rule.setter
    def clip_rule(self, clip_rule): # -> None:
        ...
    
    @property
    def clip_units(self):
        """(:class:`basestring`) The current clip units. It also can be set.
        It's a string value from :const:`CLIP_PATH_UNITS` list.

        .. versionadded:: 0.4.0
        """
        ...
    
    @clip_units.setter
    def clip_units(self, clip_unit): # -> None:
        ...
    
    @property
    def fill_color(self): # -> Color:
        """(:class:`~wand.color.Color`) The current color to fill.
        It also can be set.

        """
        ...
    
    @fill_color.setter
    def fill_color(self, color): # -> None:
        ...
    
    @property
    def fill_opacity(self): # -> Any:
        """(:class:`~numbers.Real`) The current fill opacity.
        It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @fill_opacity.setter
    def fill_opacity(self, opacity): # -> None:
        ...
    
    @property
    def fill_rule(self):
        """(:class:`basestring`) The current fill rule. It can also be set.
        It's a string value from :const:`FILL_RULE_TYPES` list.

        .. versionadded:: 0.4.0
        """
        ...
    
    @fill_rule.setter
    def fill_rule(self, fill_rule): # -> None:
        ...
    
    @property
    def font(self): # -> bytes | None:
        """(:class:`basestring`) The current font name.  It also can be set.

        .. versionchanged: 0.4.1
           Safely release allocated memory with
           :c:func:`MagickRelinquishMemory` instead of :c:func:`libc.free`.

        """
        ...
    
    @font.setter
    def font(self, font): # -> None:
        ...
    
    @property
    def font_family(self): # -> bytes | None:
        """(:class:`basestring`) The current font family. It also can be set.

        .. versionadded:: 0.4.0

        .. versionchanged: 0.4.1
           Safely release allocated memory with
           :c:func:`MagickRelinquishMemory` instead of :c:func:`libc.free`.

        """
        ...
    
    @font_family.setter
    def font_family(self, family): # -> None:
        ...
    
    @property
    def font_resolution(self): # -> tuple[float, float]:
        """(:class:`~collections.abc.Sequence`) The current font resolution.
        It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @font_resolution.setter
    def font_resolution(self, resolution): # -> None:
        ...
    
    @property
    def font_size(self): # -> Any:
        """(:class:`numbers.Real`) The font size.  It also can be set."""
        ...
    
    @font_size.setter
    def font_size(self, size): # -> None:
        ...
    
    @property
    def font_stretch(self):
        """(:class:`basestring`) The current font stretch variation.
        It also can be set, but will only apply if the font-family or encoder
        supports the stretch type.

        .. versionadded:: 0.4.0
        """
        ...
    
    @font_stretch.setter
    def font_stretch(self, stretch): # -> None:
        ...
    
    @property
    def font_style(self):
        """(:class:`basestring`) The current font style.
        It also can be set, but will only apply if the font-family
        supports the style.

        .. versionadded:: 0.4.0
        """
        ...
    
    @font_style.setter
    def font_style(self, style): # -> None:
        ...
    
    @property
    def font_weight(self): # -> Any:
        """(:class:`~numbers.Integral`) The current font weight.
        It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @font_weight.setter
    def font_weight(self, weight): # -> None:
        ...
    
    @property
    def gravity(self):
        """(:class:`basestring`) The text placement gravity used when
        annotating with text.  It's a string from :const:`GRAVITY_TYPES`
        list.  It also can be set.

        """
        ...
    
    @gravity.setter
    def gravity(self, value): # -> None:
        ...
    
    @property
    def opacity(self): # -> Any:
        """(:class:`~numbers.Real`) returns the opacity used when drawing with
        the fill or stroke color or texture. Fully opaque is 1.0. This method
        only affects vector graphics, and is experimental. To set the opacity
        of a drawing, use
        :attr:`Drawing.fill_opacity` & :attr:`Drawing.stroke_opacity`

        .. versionadded:: 0.4.0
        """
        ...
    
    @opacity.setter
    def opacity(self, opaque): # -> None:
        ...
    
    @property
    def stroke_antialias(self): # -> bool:
        """(:class:`bool`) Controls whether stroked outlines are antialiased.
        Stroked outlines are antialiased by default. When antialiasing is
        disabled stroked pixels are thresholded to determine if the stroke
        color or underlying canvas color should be used.

        It also can be set.

        .. versionadded:: 0.4.0

        """
        ...
    
    @stroke_antialias.setter
    def stroke_antialias(self, stroke_antialias): # -> None:
        ...
    
    @property
    def stroke_color(self): # -> Color:
        """(:class:`~wand.color.Color`) The current color of stroke.
        It also can be set.

        .. versionadded:: 0.3.3

        """
        ...
    
    @stroke_color.setter
    def stroke_color(self, color): # -> None:
        ...
    
    @property
    def stroke_dash_array(self): # -> list[float]:
        """(:class:`~collections.abc.Sequence`) - (:class:`numbers.Real`) An
        array representing the pattern of dashes & gaps used to stroke paths.
        It also can be set.

        .. versionadded:: 0.4.0

        .. versionchanged: 0.4.1
           Safely release allocated memory with
           :c:func:`MagickRelinquishMemory` instead of :c:func:`libc.free`.

        """
        ...
    
    @stroke_dash_array.setter
    def stroke_dash_array(self, dash_array): # -> None:
        ...
    
    @property
    def stroke_dash_offset(self): # -> Any:
        """(:class:`numbers.Real`) The stroke dash offset. It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @stroke_dash_offset.setter
    def stroke_dash_offset(self, offset): # -> None:
        ...
    
    @property
    def stroke_line_cap(self):
        """(:class:`basestring`) The stroke line cap. It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @stroke_line_cap.setter
    def stroke_line_cap(self, line_cap): # -> None:
        ...
    
    @property
    def stroke_line_join(self):
        """(:class:`basestring`) The stroke line join. It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @stroke_line_join.setter
    def stroke_line_join(self, line_join): # -> None:
        ...
    
    @property
    def stroke_miter_limit(self): # -> Any:
        """(:class:`~numbers.Integral`) The current miter limit.
        It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @stroke_miter_limit.setter
    def stroke_miter_limit(self, miter_limit): # -> None:
        ...
    
    @property
    def stroke_opacity(self): # -> Any:
        """(:class:`~numbers.Real`) The current stroke opacity.
        It also can be set.

        .. versionadded:: 0.4.0
        """
        ...
    
    @stroke_opacity.setter
    def stroke_opacity(self, opacity): # -> None:
        ...
    
    @property
    def stroke_width(self): # -> Any:
        """(:class:`numbers.Real`) The stroke width.  It also can be set.

        .. versionadded:: 0.3.3

        """
        ...
    
    @stroke_width.setter
    def stroke_width(self, width): # -> None:
        ...
    
    @property
    def text_alignment(self):
        """(:class:`basestring`) The current text alignment setting.
        It's a string value from :const:`TEXT_ALIGN_TYPES` list.
        It also can be set.

        """
        ...
    
    @text_alignment.setter
    def text_alignment(self, align): # -> None:
        ...
    
    @property
    def text_antialias(self): # -> bool:
        """(:class:`bool`) The boolean value which represents whether
        antialiasing is used for text rendering.  It also can be set to
        ``True`` or ``False`` to switch the setting.

        """
        ...
    
    @text_antialias.setter
    def text_antialias(self, value): # -> None:
        ...
    
    @property
    def text_decoration(self):
        """(:class:`basestring`) The text decoration setting, a string
        from :const:`TEXT_DECORATION_TYPES` list.  It also can be set.

        """
        ...
    
    @text_decoration.setter
    def text_decoration(self, decoration): # -> None:
        ...
    
    @property
    def text_direction(self):
        """(:class:`basestring`) The text direction setting. a string
        from :const:`TEXT_DIRECTION_TYPES` list. It also can be set."""
        ...
    
    @text_direction.setter
    def text_direction(self, direction): # -> None:
        ...
    
    @property
    def text_encoding(self): # -> bytes | None:
        """(:class:`basestring`) The internally used text encoding setting.
        Although it also can be set, but it's not encouraged.

        .. versionchanged: 0.4.1
           Safely release allocated memory with
           :c:func:`MagickRelinquishMemory` instead of :c:func:`libc.free`.

        """
        ...
    
    @text_encoding.setter
    def text_encoding(self, encoding): # -> None:
        ...
    
    @property
    def text_interline_spacing(self): # -> Any:
        """(:class:`numbers.Real`) The setting of the text line spacing.
        It also can be set.

        """
        ...
    
    @text_interline_spacing.setter
    def text_interline_spacing(self, spacing): # -> None:
        ...
    
    @property
    def text_interword_spacing(self): # -> Any:
        """(:class:`numbers.Real`) The setting of the word spacing.
        It also can be set.

        """
        ...
    
    @text_interword_spacing.setter
    def text_interword_spacing(self, spacing): # -> None:
        ...
    
    @property
    def text_kerning(self): # -> Any:
        """(:class:`numbers.Real`) The setting of the text kerning.
        It also can be set.

        """
        ...
    
    @text_kerning.setter
    def text_kerning(self, kerning): # -> None:
        ...
    
    @property
    def text_under_color(self): # -> Color:
        """(:class:`~wand.color.Color`) The color of a background rectangle
        to place under text annotations.  It also can be set.

        """
        ...
    
    @text_under_color.setter
    def text_under_color(self, color): # -> None:
        ...
    
    @property
    def vector_graphics(self):
        """(:class:`basestring`) The XML text of the Vector Graphics.
        It also can be set.  The drawing-wand XML is experimental,
        and subject to change.

        Setting this property to None will reset all vector graphic properties
        to the default state.

        .. versionadded:: 0.4.0

        .. versionchanged: 0.4.1
           Safely release allocated memory with
           :c:func:`MagickRelinquishMemory` instead of :c:func:`libc.free`.

        """
        ...
    
    @vector_graphics.setter
    def vector_graphics(self, vector_graphics): # -> None:
        ...
    
    def affine(self, matrix): # -> None:
        """Adjusts the current affine transformation matrix with the specified
        affine transformation matrix. Note that the current affine transform is
        adjusted rather than replaced.

        .. sourcecode:: text

                                              | sx  rx  0 |
            | x', y', 1 |  =  | x, y, 1 |  *  | ry  sy  0 |
                                              | tx  ty  1 |

        :param matrix: a list of :class:`~numbers.Real` to define affine
                       matrix ``[sx, rx, ry, sy, tx, ty]``
        :type matrix: :class:`collections.abc.Sequence`

        .. versionadded:: 0.4.0

        """
        ...
    
    def alpha(self, x=..., y=..., paint_method=...): # -> None:
        """Paints on the image's opacity channel in order to set effected
        pixels to transparent.

         To influence the opacity of pixels. The available methods are:

        - ``'undefined'``
        - ``'point'``
        - ``'replace'``
        - ``'floodfill'``
        - ``'filltoborder'``
        - ``'reset'``

        .. note::

            This method replaces :meth:`matte()` in ImageMagick version 7.
            An :class:`AttributeError` will be raised if attempting
            to call on a library without ``DrawAlpha`` support.

        .. versionadded:: 0.5.0

        """
        ...
    
    def arc(self, start, end, degree): # -> None:
        """Draws a arc using the current :attr:`stroke_color`,
        :attr:`stroke_width`, and :attr:`fill_color`.

        :param start: (:class:`~numbers.Real`, :class:`numbers.Real`)
                      pair which represents starting x and y of the arc
        :type start: :class:`~collections.abc.Sequence`
        :param end: (:class:`~numbers.Real`, :class:`numbers.Real`)
                      pair which represents ending x and y of the arc
        :type end: :class:`~collections.abc.Sequence`
        :param degree: (:class:`~numbers.Real`, :class:`numbers.Real`)
                      pair which represents starting degree, and ending degree
        :type degree: :class:`~collections.abc.Sequence`

        .. versionadded:: 0.4.0

        """
        ...
    
    def bezier(self, points=...): # -> None:
        """Draws a bezier curve through a set of points on the image, using
        the specified array of coordinates.

        At least four points should be given to complete a bezier path.
        The first & forth point being the start & end point, and the second
        & third point controlling the direction & curve.

        Example bezier on ``image`` ::

            with Drawing() as draw:
                points = [(40,10), # Start point
                          (20,50), # First control
                          (90,10), # Second control
                          (70,40)] # End point
                draw.stroke_color = Color('#000')
                draw.fill_color = Color('#fff')
                draw.bezier(points)
                draw.draw(image)

        :param points: list of x,y tuples
        :type points: :class:`list`

        .. versionadded:: 0.4.0

        """
        ...
    
    def circle(self, origin, perimeter): # -> None:
        """Draws a circle from ``origin`` to ``perimeter``

        :param origin: (:class:`~numbers.Real`, :class:`numbers.Real`)
                       pair which represents origin x and y of circle
        :type origin: :class:`collections.abc.Sequence`
        :param perimeter: (:class:`~numbers.Real`, :class:`numbers.Real`)
                       pair which represents perimeter x and y of circle
        :type perimeter: :class:`collections.abc.Sequence`

        .. versionadded:: 0.4.0

        """
        ...
    
    def clear(self): # -> None:
        ...
    
    def clone(self): # -> Self:
        """Copies a drawing object.

        :returns: a duplication
        :rtype: :class:`Drawing`

        """
        ...
    
    def color(self, x=..., y=..., paint_method=...): # -> None:
        """Draws a color on the image using current fill color, starting
        at specified position & method.

        Available methods in :class:`wand.drawing.PAINT_METHOD_TYPES`:

        - ``'undefined'``
        - ``'point'``
        - ``'replace'``
        - ``'floodfill'``
        - ``'filltoborder'``
        - ``'reset'``

        .. versionadded:: 0.4.0

        """
        ...
    
    def comment(self, message=...): # -> None:
        """Adds a comment to the vector stream.

        :param message: the comment to set.
        :type message: :class:`basestring`

        .. versionadded:: 0.4.0
        """
        ...
    
    def composite(self, operator, left, top, width, height, image): # -> None:
        """Composites an image onto the current image, using the specified
        composition operator, specified position, and at the specified size.

        :param operator: the operator that affects how the composite
                         is applied to the image.  available values
                         can be found in the :const:`COMPOSITE_OPERATORS`
                         list
        :param type: :const:`COMPOSITE_OPERATORS`
        :param left: the column offset of the composited drawing source
        :type left: :class:`numbers.Real`
        :param top: the row offset of the composited drawing source
        :type top: :class:`numbers.Real`
        :param width: the total columns to include in the composited source
        :type width: :class:`numbers.Real`
        :param height: the total rows to include in the composited source
        :type height: :class:`numbers.Real`

        .. versionadded:: 0.4.0

        """
        ...
    
    def draw(self, image): # -> None:
        """Renders the current drawing into the ``image``.  You can simply
        call :class:`Drawing` instance rather than calling this method.
        That means the following code which calls :class:`Drawing` object
        itself::

            drawing(image)

        is equivalent to the following code which calls :meth:`draw()` method::

            drawing.draw(image)

        :param image: the image to be drawn
        :type image: :class:`~wand.image.BaseImage`

        """
        ...
    
    def ellipse(self, origin, radius, rotation=...): # -> None:
        """Draws a ellipse at ``origin`` with independent x & y ``radius``.
        Ellipse can be partial by setting start & end ``rotation``.

        :param origin: (:class:`~numbers.Real`, :class:`numbers.Real`)
                       pair which represents origin x and y of circle
        :type origin: :class:`collections.abc.Sequence`
        :param radius: (:class:`~numbers.Real`, :class:`numbers.Real`)
                       pair which represents radius x and radius y of circle
        :type radius: :class:`collections.abc.Sequence`
        :param rotation: (:class:`~numbers.Real`, :class:`numbers.Real`)
                         pair which represents start and end of ellipse.
                         Default (0,360)
        :type rotation: :class:`collections.abc.Sequence`

        .. versionadded:: 0.4.0

        """
        ...
    
    def get_font_metrics(self, image, text, multiline=...): # -> FontMetrics:
        """Queries font metrics by cloning the ``image``, and rendering
        the ``text`` with the font properties defined on :class:`Drawing`.

        This is useful for determining the size of the rendered text. Set
        ``multiline`` to ``True`` if the given ``text`` contains line-breaks.

        The return value is an instance of :class:`FontMetrics` which
        has the attributes of the text's rendered size, max horizontal advance,
        and distance of ascent & descent from the baseline.

        :param image: the image to be drawn
        :type image: :class:`~wand.image.BaseImage`
        :param text: the text string for get font metrics.
        :type text: :class:`basestring`
        :param multiline: text is multiline or not
        :type multiline: `boolean`
        :returns: :class:`FontMetrics`

        .. versionadded:: 0.3.0
        """
        ...
    
    def line(self, start, end): # -> None:
        """Draws a line ``start`` to ``end``.

        :param start: (:class:`~numbers.Integral`, :class:`numbers.Integral`)
                      pair which represents starting x and y of the line
        :type start: :class:`collections.abc.Sequence`
        :param end: (:class:`~numbers.Integral`, :class:`numbers.Integral`)
                    pair which represents ending x and y of the line
        :type end: :class:`collections.abc.Sequence`

        """
        ...
    
    def matte(self, x=..., y=..., paint_method=...): # -> None:
        """Paints on the image's opacity channel in order to set effected
        pixels to transparent.

         To influence the opacity of pixels. The available methods are:

        - ``'undefined'``
        - ``'point'``
        - ``'replace'``
        - ``'floodfill'``
        - ``'filltoborder'``
        - ``'reset'``

        .. note::

            This method has been replace by :meth:`alpha()` in ImageMagick
            version 7. An :class:`AttributeError` will be raised if attempting
            to call on a library without ``DrawMatte`` support.

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_close(self): # -> Self:
        """Adds a path element to the current path which closes
        the current subpath by drawing a straight line from the current point
        to the current subpath's most recent starting point.

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_curve(self, to=..., controls=..., smooth=..., relative=...): # -> Self:
        """Draws a cubic Bezier curve from the current point to given ``to``
        (x,y) coordinate using ``controls`` points at the beginning and
        the end of the curve.
        If ``smooth`` is set to True, only one ``controls`` is expected
        and the previous control is used, else two pair of coordinates are
        expected to define the control points. The ``to`` coordinate then
        becomes the new current point.

        :param to: (:class:`~numbers.Real`, :class:`numbers.Real`)
                   pair which represents coordinates to draw to
        :type to: :class:`collections.abc.Sequence`
        :param controls: (:class:`~numbers.Real`, :class:`numbers.Real`)
                         coordinate to used to influence curve
        :type controls: :class:`collections.abc.Sequence`
        :param smooth: :class:`bool` assume last defined control coordinate
        :type smooth: :class:`bool`
        :param relative: treat given coordinates as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_curve_to_quadratic_bezier(self, to=..., control=..., smooth=..., relative=...): # -> Self:
        """Draws a quadratic Bezier curve from the current point to given
        ``to`` coordinate. The control point is assumed to be the reflection of
        the control point on the previous command if ``smooth`` is True, else a
        pair of ``control`` coordinates must be given. Each coordinates can be
        relative, or absolute, to the current point by setting the ``relative``
        flag. The ``to`` coordinate then becomes the new current point, and the
        ``control`` coordinate will be assumed when called again
        when ``smooth`` is set to true.

        :param to: (:class:`~numbers.Real`, :class:`numbers.Real`)
                   pair which represents coordinates to draw to
        :type to: :class:`collections.abc.Sequence`
        :param control: (:class:`~numbers.Real`, :class:`numbers.Real`)
                        coordinate to used to influence curve
        :type control: :class:`collections.abc.Sequence`
        :param smooth: assume last defined control coordinate
        :type smooth: :class:`bool`
        :param relative: treat given coordinates as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_elliptic_arc(self, to=..., radius=..., rotation=..., large_arc=..., clockwise=..., relative=...): # -> Self:
        """Draws an elliptical arc from the current point to given ``to``
        coordinates. The ``to`` coordinates can be relative, or absolute,
        to the current point by setting the ``relative`` flag.
        The size and orientation of the ellipse are defined by
        two radii (rx, ry) in ``radius`` and an ``rotation`` parameters,
        which indicates how the ellipse as a whole is
        rotated relative to the current coordinate system. The center of the
        ellipse is calculated automagically to satisfy the constraints imposed
        by the other parameters. ``large_arc`` and ``clockwise`` contribute to
        the automatic calculations and help determine how the arc is drawn.
        If ``large_arc`` is True then draw the larger of the available arcs.
        If ``clockwise`` is true, then draw the arc matching a clock-wise
        rotation.

        :param to: (:class:`~numbers.Real`, :class:`numbers.Real`)
                   pair which represents coordinates to draw to
        :type to: :class:`collections.abc.Sequence`
        :param radius: (:class:`~numbers.Real`, :class:`numbers.Real`)
                       pair which represents the radii of the ellipse to draw
        :type radius: :class:`collections.abc.Sequence`
        :param rotate: degree to rotate ellipse on x-axis
        :type rotate: :class:`~numbers.Real`
        :param large_arc: draw largest available arc
        :type large_arc: :class:`bool`
        :param clockwise: draw arc path clockwise from start to target
        :type clockwise: :class:`bool`
        :param relative: treat given coordinates as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_finish(self): # -> Self:
        """Terminates the current path.

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_horizontal_line(self, x=..., relative=...): # -> Self:
        """Draws a horizontal line path from the current point to the target
        point. Given ``x`` parameter can be relative, or absolute, to the
        current point by setting the ``relative`` flag. The target point then
        becomes the new current point.

        :param x: :class:`~numbers.Real`
                      x-axis point to draw to.
        :type x: :class:`~numbers.Real`
        :param relative: :class:`bool`
                    treat given point as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_line(self, to=..., relative=...): # -> Self:
        """Draws a line path from the current point to the given ``to``
        coordinate. The ``to`` coordinates can be relative, or absolute, to the
        current point by setting the ``relative`` flag. The coordinate then
        becomes the new current point.

        :param to: (:class:`~numbers.Real`, :class:`numbers.Real`)
                      pair which represents coordinates to draw to.
        :type to: :class:`collections.abc.Sequence`
        :param relative: :class:`bool`
                    treat given coordinates as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_move(self, to=..., relative=...): # -> Self:
        """Starts a new sub-path at the given coordinates. Given ``to``
        parameter can be relative, or absolute, by setting the ``relative``
        flag.

        :param to: (:class:`~numbers.Real`, :class:`numbers.Real`)
                      pair which represents coordinates to draw to.
        :type to: :class:`collections.abc.Sequence`
        :param relative: :class:`bool`
                    treat given coordinates as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_start(self): # -> Self:
        """Declares the start of a path drawing list which is terminated by a
        matching :meth:`path_finish()` command. All other `path_*` commands
        must be enclosed between a :meth:`path_start()` and a
        :meth:`path_finish()` command. This is because path drawing commands
        are subordinate commands and they do not function by themselves.

        .. versionadded:: 0.4.0

        """
        ...
    
    def path_vertical_line(self, y=..., relative=...): # -> Self:
        """Draws a vertical line path from the current point to the target
        point. Given ``y`` parameter can be relative, or absolute, to the
        current point by setting the ``relative`` flag. The target point then
        becomes the new current point.

        :param y: :class:`~numbers.Real`
                      y-axis point to draw to.
        :type y: :class:`~numbers.Real`
        :param relative: :class:`bool`
                    treat given point as relative to current point
        :type relative: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def polygon(self, points=...): # -> None:
        """Draws a polygon using the current :attr:`stroke_color`,
        :attr:`stroke_width`, and :attr:`fill_color`, using the specified
        array of coordinates.

        Example polygon on ``image`` ::

            with Drawing() as draw:
                points = [(40,10), (20,50), (90,10), (70,40)]
                draw.polygon(points)
                draw.draw(image)

        :param points: list of x,y tuples
        :type points: :class:`list`

        .. versionadded:: 0.4.0

        """
        ...
    
    def polyline(self, points=...): # -> None:
        """Draws a polyline using the current :attr:`stroke_color`,
        :attr:`stroke_width`, and :attr:`fill_color`, using the specified
        array of coordinates.

        Identical to :class:`~wand.drawing.Drawing.polygon`, but without closed
        stroke line.

        :param points: list of x,y tuples
        :type points: :class:`list`

        .. versionadded:: 0.4.0

        """
        ...
    
    def point(self, x, y): # -> None:
        """Draws a point at given ``x`` and ``y``

        :param x: :class:`~numbers.Real` x of point
        :type x: :class:`~numbers.Real`
        :param y: :class:`~numbers.Real` y of point
        :type y: :class:`~numbers.Real`

        .. versionadded:: 0.4.0

        """
        ...
    
    def pop(self): # -> bool:
        """Pop destroys the current tip of the drawing context stack,
        and restores the parent style context.
        See :meth:`push()` method for an example.

        .. note::

            Popping the graphical context stack will not erase,
            or alter, any previously executed drawing commands.

        :returns: success of pop operation.
        :rtype: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def pop_clip_path(self): # -> None:
        """Terminates a clip path definition.

        .. versionadded:: 0.4.0

        """
        ...
    
    def pop_defs(self): # -> None:
        """Terminates a definition list.

        .. versionadded:: 0.4.0

        """
        ...
    
    def pop_pattern(self): # -> None:
        """Terminates a pattern definition.

        .. versionadded:: 0.4.0

        """
        ...
    
    def push(self): # -> bool:
        """Grows the current drawing context stack by one, and inherits
        the previous style attributes. Use :class:`Drawing.pop` to return
        to restore previous style attributes.

        This is useful for drawing shapes with different styles
        without repeatedly setting the similar
        :meth:`fill_color <wand.drawing.Drawing.fill_color>` &
        :meth:`stroke_color <wand.drawing.Drawing.stroke_color>` properties.

        For example::

            with Drawing() as ctx:
                ctx.fill_color = Color('GREEN')
                ctx.stroke_color = Color('ORANGE')
                ctx.push()
                ctx.fill_color = Color('RED')
                ctx.text(x1, y1, 'this is RED with ORANGE outline')
                ctx.push()
                ctx.stroke_color = Color('BLACK')
                ctx.text(x2, y2, 'this is RED with BLACK outline')
                ctx.pop()
                ctx.pop()
                ctx.text(x3, y3, 'this is GREEN with ORANGE outline')

        Which translate to the following MVG::

            push graphic-context
                fill "GREEN"
                stroke "ORANGE"
                push graphic-context
                    fill "RED"
                    text x1,y1 "this is RED with ORANGE outline"
                    push graphic-context
                        stroke "BLACK"
                        text x2,y2 "this is RED with BLACK outline"
                    pop graphic-context
                pop graphic-context
                text x3,y3 "this is GREEN with ORANGE outline"
            pop graphic-context

        .. note::

            Pushing graphical context does not reset any previously
            drawn artifacts.

        :returns: success of push operation.
        :rtype: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def push_clip_path(self, clip_mask_id): # -> None:
        """Starts a clip path definition which is comprised of any number of
        drawing commands and terminated by a :class:`Drawing.pop_clip_path`
        command.

        :param clip_mask_id: string identifier to associate with the clip path.
        :type clip_mask_id: :class:`basestring`

        .. versionadded:: 0.4.0

        """
        ...
    
    def push_defs(self): # -> None:
        """Indicates that commands up to a terminating
        :class:`Drawing.pop_defs` command create named elements (e.g.
        clip-paths, textures, etc.) which may safely be processed earlier for
        the sake of efficiency.

        .. versionadded:: 0.4.0

        """
        ...
    
    def push_pattern(self, pattern_id, left, top, width, height): # -> bool:
        """Indicates that subsequent commands up to a
        :class:`Drawing.pop_pattern` command comprise the definition of a named
        pattern. The pattern space is assigned top left corner coordinates, a
        width and height, and becomes its own drawing space. Anything which can
        be drawn may be used in a pattern definition.
        Named patterns may be used as stroke or brush definitions.

        :param pattern_id: a unique identifier for the pattern.
        :type pattern_id: :class:`basestring`
        :param left: x ordinate of top left corner.
        :type left: :class:`numbers.Real`
        :param top: y ordinate of top left corner.
        :type top: :class:`numbers.Real`
        :param width: width of pattern space.
        :type width: :class:`numbers.Real`
        :param height: height of pattern space.
        :type height: :class:`numbers.Real`
        :returns: success of push operation
        :rtype: :class:`bool`

        .. versionadded:: 0.4.0

        """
        ...
    
    def rectangle(self, left=..., top=..., right=..., bottom=..., width=..., height=..., radius=..., xradius=..., yradius=...): # -> None:
        """Draws a rectangle using the current :attr:`stroke_color`,
        :attr:`stroke_width`, and :attr:`fill_color`.

        .. sourcecode:: text

           +--------------------------------------------------+
           |              ^                         ^         |
           |              |                         |         |
           |             top                        |         |
           |              |                         |         |
           |              v                         |         |
           | <-- left --> +-------------------+  bottom       |
           |              |             ^     |     |         |
           |              | <-- width --|---> |     |         |
           |              |           height  |     |         |
           |              |             |     |     |         |
           |              |             v     |     |         |
           |              +-------------------+     v         |
           | <--------------- right ---------->               |
           +--------------------------------------------------+

        :param left: x-offset of the rectangle to draw
        :type left: :class:`numbers.Real`
        :param top: y-offset of the rectangle to draw
        :type top: :class:`numbers.Real`
        :param right: second x-offset of the rectangle to draw.
                      this parameter and ``width`` parameter are exclusive
                      each other
        :type right: :class:`numbers.Real`
        :param bottom: second y-offset of the rectangle to draw.
                       this parameter and ``height`` parameter are exclusive
                       each other
        :type bottom: :class:`numbers.Real`
        :param width: the :attr:`width` of the rectangle to draw.
                      this parameter and ``right`` parameter are exclusive
                      each other
        :type width: :class:`numbers.Real`
        :param height: the :attr:`height` of the rectangle to draw.
                       this parameter and ``bottom`` parameter are exclusive
                       each other
        :type height: :class:`numbers.Real`
        :param radius: the corner rounding. this is a short-cut for setting
                       both :attr:`xradius`, and :attr:`yradius`
        :type radius: :class:`numbers.Real`
        :param xradius: the :attr:`xradius` corner in horizontal direction.
        :type xradius: :class:`numbers.Real`
        :param yradius: the :attr:`yradius` corner in vertical direction.
        :type yradius: :class:`numbers.Real`

        .. versionadded:: 0.3.6

        .. versionchanged:: 0.4.0
           Radius keywords added to create rounded rectangle.

        """
        ...
    
    def rotate(self, degree=...): # -> None:
        """Applies the specified rotation to the current coordinate space.

        :param degree: degree to rotate
        :type degree: :class:`~numbers.Real`

        .. versionadded:: 0.4.0

        """
        ...
    
    def scale(self, x=..., y=...): # -> None:
        """
        Adjusts the scaling factor to apply in the horizontal and vertical
        directions to the current coordinate space.

        :param x: Horizontal scale factor. Default `1.0`
        :type x: :class:`~numbers.Real`
        :param y: Vertical scale factor. Default `1.0`
        :type y: :class:`~numbers.Real`

        .. versionadded:: 0.4.0

        """
        ...
    
    def set_fill_pattern_url(self, url): # -> None:
        """Sets the URL to use as a fill pattern for filling objects. Only
        local URLs ("#identifier") are supported at this time. These local URLs
        are normally created by defining a named fill pattern with
        Drawing.push_pattern & Drawing.pop_pattern.

        :param url: URL to use to obtain fill pattern.
        :type url: :class:`basestring`

        .. versionadded:: 0.4.0

        """
        ...
    
    def set_stroke_pattern_url(self, url): # -> None:
        """Sets the pattern used for stroking object outlines. Only local
        URLs ("#identifier") are supported at this time. These local URLs are
        normally created by defining a named stroke pattern with
        Drawing.push_pattern & Drawing.pop_pattern.

        :param url: URL to use to obtain stroke pattern.
        :type url: :class:`basestring`

        .. versionadded:: 0.4.0

        """
        ...
    
    def skew(self, x=..., y=...): # -> None:
        """Skews the current coordinate system in the horizontal direction if
        ``x`` is given, and vertical direction if ``y`` is given.

        :param x: Skew horizontal direction
        :type x: :class:`~numbers.Real`
        :param y: Skew vertical direction
        :type y: :class:`~numbers.Real`

        .. versionadded:: 0.4.0

        """
        ...
    
    def text(self, x, y, body): # -> None:
        """Writes a text ``body`` into (``x``, ``y``).

        :param x: the left offset where to start writing a text
        :type x: :class:`numbers.Integral`
        :param y: the baseline where to start writing text
        :type y: :class:`numbers.Integral`
        :param body: the body string to write
        :type body: :class:`basestring`

        """
        ...
    
    def translate(self, x=..., y=...): # -> None:
        """Applies a translation to the current coordinate system which moves
        the coordinate system origin to the specified coordinate.

        :param x: Skew horizontal direction
        :type x: :class:`~numbers.Real`
        :param y: Skew vertical direction
        :type y: :class:`~numbers.Real`

        .. versionadded:: 0.4.0
        """
        ...
    
    def viewbox(self, left, top, right, bottom): # -> None:
        """Viewbox sets the overall canvas size to be recorded with the drawing
        vector data. Usually this will be specified using the same size as the
        canvas image. When the vector data is saved to SVG or MVG formats, the
        viewbox is use to specify the size of the canvas image that a viewer
        will render the vector data on.

        :param left: the left most point of the viewbox.
        :type left: :class:`~numbers.Integral`
        :param top: the top most point of the viewbox.
        :type top: :class:`~numbers.Integral`
        :param right: the right most point of the viewbox.
        :type right: :class:`~numbers.Integral`
        :param bottom: the bottom most point of the viewbox.
        :type bottom: :class:`~numbers.Integral`

        .. versionadded:: 0.4.0

        """
        ...
    
    def __call__(self, image): # -> None:
        ...
    


class FontMetrics(collections.namedtuple('FontMetrics', FONT_METRICS_ATTRIBUTES)):
    """
    The tuple subtype which consists of font metrics data.

    Pixel values can be converted to points by the following:

    .. math::

        points = \\frac{pixels \\ast 72}{resolution}

    .. py:attribute:: character_width

        (:class:`numbers.Real`) The horizontal value of the ``x`` in pixels.

    .. py:attribute:: character_height

        (:class:`numbers.Real`) The vertical value of the ``x`` in pixels.

    .. py:attribute:: ascender

        (:class:`numbers.Real`) The largest distance from the text baseline
        to the highest point above the x-height. This value should always be
        positive.

    .. py:attribute:: descender

        (:class:`numbers.Real`) The farthest distance from the text baseline
        to the lowest point below the x-height. This value should always be
        negative.

    .. py:attribute:: text_width

        (:class:`numbers.Real`) The full width of the text.

    .. py:attribute:: text_height

        (:class:`numbers.Real`) The full height of the text.

    .. py:attribute:: maximum_horizontal_advance

        (:class:`numbers.Real`) The largest distance from the start of one
        character to the start of the following character.

    .. py:attribute:: x1

        (:class:`numbers.Real`) The horizontal value of the bounding box's
        starting corner.

    .. py:attribute:: y1

        (:class:`numbers.Real`) The vertical value of the bounding box's
        starting corner.

    .. py:attribute:: x2

        (:class:`numbers.Real`) The horizontal value of the bounding box's
        ending corner.

    .. py:attribute:: y2

        (:class:`numbers.Real`) The vertical value of the bounding box's
        ending corner.

    .. py:attribute:: x

        (:class:`numbers.Real`) The horizontal value of the origin.

    .. py:attribute:: y

        (:class:`numbers.Real`) The vertical value of the origin.

    .. note::

        When using :meth:`~wand.drawing.Drawing.get_font_metrics`, the returned
        attributes ``x1``, ``y1``, ``x2``, ``y2``, ``x`` and ``y`` can be
        ignored as they are used for internal FreeType rendering, and have no
        meaningful context.

    .. versionadded:: 0.3.0

    .. versionchanged:: 0.6.8
       Created sub-class of the namedtuple to improve auto-documentation.
    """
    def size(self): # -> tuple[Any, Any]:
        """Short-cut method for the width & height of the rendered text.

        :returns: (width, height)

        .. versionadded:: 0.6.8
        """
        ...
    


