"""
This type stub file was generated by pyright.
"""

""":mod:`wand.exceptions` --- Errors and warnings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module maps MagickWand API's errors and warnings to Python's native
exceptions and warnings. You can catch all MagickWand errors using Python's
natural way to catch errors.

.. seealso::

   `ImageMagick Exceptions <http://www.imagemagick.org/script/exception.php>`_

.. versionadded:: 0.1.1

.. versionchanged:: 0.5.8
   Warning & Error Exceptions are now explicitly defined. Previously
   ImageMagick domain-based errors were dynamically generated at runtime.
"""
class WandException(Exception):
    """All Wand-related exceptions are derived from this class."""
    ...


class BaseWarning(WandException, Warning):
    """Base class for Wand-related warnings.

    .. versionadded:: 0.4.4

    """
    ...


class BaseError(WandException):
    """Base class for Wand-related errors.

    .. versionadded:: 0.4.4

    """
    ...


class BaseFatalError(WandException):
    """Base class for Wand-related fatal errors.

    .. versionadded:: 0.4.4

    """
    ...


class WandLibraryVersionError(WandException):
    """Base class for Wand-related ImageMagick version errors.

    .. versionadded:: 0.3.2

    """
    ...


class WandRuntimeError(WandException, RuntimeError):
    """Generic class for Wand-related runtime errors.

    .. versionadded:: 0.5.2
    """
    ...


class ResourceLimitWarning(BaseWarning, MemoryError):
    """A program resource is exhausted e.g. not enough memory."""
    wand_error_code = ...


class ResourceLimitError(BaseError, MemoryError):
    """A program resource is exhausted e.g. not enough memory."""
    wand_error_code = ...


class ResourceLimitFatalError(BaseFatalError, MemoryError):
    """A program resource is exhausted e.g. not enough memory."""
    wand_error_code = ...


class TypeWarning(BaseWarning):
    """A font is unavailable; a substitution may have occurred."""
    wand_error_code = ...


class TypeError(BaseError):
    """A font is unavailable; a substitution may have occurred."""
    wand_error_code = ...


class TypeFatalError(BaseFatalError):
    """A font is unavailable; a substitution may have occurred."""
    wand_error_code = ...


class OptionWarning(BaseWarning):
    """A command-line option was malformed."""
    wand_error_code = ...


class OptionError(BaseError):
    """A command-line option was malformed."""
    wand_error_code = ...


class OptionFatalError(BaseFatalError):
    """A command-line option was malformed."""
    wand_error_code = ...


class DelegateWarning(BaseWarning):
    """An ImageMagick delegate failed to complete."""
    wand_error_code = ...


class DelegateError(BaseError):
    """An ImageMagick delegate failed to complete."""
    wand_error_code = ...


class DelegateFatalError(BaseFatalError):
    """An ImageMagick delegate failed to complete."""
    wand_error_code = ...


class MissingDelegateWarning(BaseWarning, ImportError):
    """The image type can not be read or written because the appropriate;
       delegate is missing."""
    wand_error_code = ...


class MissingDelegateError(BaseError, ImportError):
    """The image type can not be read or written because the appropriate;
       delegate is missing."""
    wand_error_code = ...


class MissingDelegateFatalError(BaseFatalError, ImportError):
    """The image type can not be read or written because the appropriate;
       delegate is missing."""
    wand_error_code = ...


class CorruptImageWarning(BaseWarning, ValueError):
    """The image file may be corrupt."""
    wand_error_code = ...


class CorruptImageError(BaseError, ValueError):
    """The image file may be corrupt."""
    wand_error_code = ...


class CorruptImageFatalError(BaseFatalError, ValueError):
    """The image file may be corrupt."""
    wand_error_code = ...


class FileOpenWarning(BaseWarning, IOError):
    """The image file could not be opened for reading or writing."""
    wand_error_code = ...


class FileOpenError(BaseError, IOError):
    """The image file could not be opened for reading or writing."""
    wand_error_code = ...


class FileOpenFatalError(BaseFatalError, IOError):
    """The image file could not be opened for reading or writing."""
    wand_error_code = ...


class BlobWarning(BaseWarning, IOError):
    """A binary large object could not be allocated, read, or written."""
    wand_error_code = ...


class BlobError(BaseError, IOError):
    """A binary large object could not be allocated, read, or written."""
    wand_error_code = ...


class BlobFatalError(BaseFatalError, IOError):
    """A binary large object could not be allocated, read, or written."""
    wand_error_code = ...


class StreamWarning(BaseWarning, IOError):
    """There was a problem reading or writing from a stream."""
    wand_error_code = ...


class StreamError(BaseError, IOError):
    """There was a problem reading or writing from a stream."""
    wand_error_code = ...


class StreamFatalError(BaseFatalError, IOError):
    """There was a problem reading or writing from a stream."""
    wand_error_code = ...


class CacheWarning(BaseWarning):
    """Pixels could not be read or written to the pixel cache."""
    wand_error_code = ...


class CacheError(BaseError):
    """Pixels could not be read or written to the pixel cache."""
    wand_error_code = ...


class CacheFatalError(BaseFatalError):
    """Pixels could not be read or written to the pixel cache."""
    wand_error_code = ...


class CoderWarning(BaseWarning):
    """There was a problem with an image coder."""
    wand_error_code = ...


class CoderError(BaseError):
    """There was a problem with an image coder."""
    wand_error_code = ...


class CoderFatalError(BaseFatalError):
    """There was a problem with an image coder."""
    wand_error_code = ...


class ModuleWarning(BaseWarning):
    """There was a problem with an image module."""
    wand_error_code = ...


class ModuleError(BaseError):
    """There was a problem with an image module."""
    wand_error_code = ...


class ModuleFatalError(BaseFatalError):
    """There was a problem with an image module."""
    wand_error_code = ...


class DrawWarning(BaseWarning):
    """A drawing operation failed."""
    wand_error_code = ...


class DrawError(BaseError):
    """A drawing operation failed."""
    wand_error_code = ...


class DrawFatalError(BaseFatalError):
    """A drawing operation failed."""
    wand_error_code = ...


class ImageWarning(BaseWarning):
    """The operation could not complete due to an incompatible image."""
    wand_error_code = ...


class ImageError(BaseError):
    """The operation could not complete due to an incompatible image."""
    wand_error_code = ...


class ImageFatalError(BaseFatalError):
    """The operation could not complete due to an incompatible image."""
    wand_error_code = ...


class WandWarning(BaseWarning):
    """There was a problem specific to the MagickWand API."""
    wand_error_code = ...


class WandError(BaseError):
    """There was a problem specific to the MagickWand API."""
    wand_error_code = ...


class WandFatalError(BaseFatalError):
    """There was a problem specific to the MagickWand API."""
    wand_error_code = ...


class RandomWarning(BaseWarning):
    """There is a problem generating a true or pseudo-random number."""
    wand_error_code = ...


class RandomError(BaseError):
    """There is a problem generating a true or pseudo-random number."""
    wand_error_code = ...


class RandomFatalError(BaseFatalError):
    """There is a problem generating a true or pseudo-random number."""
    wand_error_code = ...


class XServerWarning(BaseWarning):
    """An X resource is unavailable."""
    wand_error_code = ...


class XServerError(BaseError):
    """An X resource is unavailable."""
    wand_error_code = ...


class XServerFatalError(BaseFatalError):
    """An X resource is unavailable."""
    wand_error_code = ...


class MonitorWarning(BaseWarning):
    """There was a problem activating the progress monitor."""
    wand_error_code = ...


class MonitorError(BaseError):
    """There was a problem activating the progress monitor."""
    wand_error_code = ...


class MonitorFatalError(BaseFatalError):
    """There was a problem activating the progress monitor."""
    wand_error_code = ...


class RegistryWarning(BaseWarning):
    """There was a problem getting or setting the registry."""
    wand_error_code = ...


class RegistryError(BaseError):
    """There was a problem getting or setting the registry."""
    wand_error_code = ...


class RegistryFatalError(BaseFatalError):
    """There was a problem getting or setting the registry."""
    wand_error_code = ...


class ConfigureWarning(BaseWarning):
    """There was a problem getting a configuration file."""
    wand_error_code = ...


class ConfigureError(BaseError):
    """There was a problem getting a configuration file."""
    wand_error_code = ...


class ConfigureFatalError(BaseFatalError):
    """There was a problem getting a configuration file."""
    wand_error_code = ...


class PolicyWarning(BaseWarning):
    """A policy denies access to a delegate, coder, filter, path, or
       resource."""
    wand_error_code = ...


class PolicyError(BaseError):
    """A policy denies access to a delegate, coder, filter, path, or
       resource."""
    wand_error_code = ...


class PolicyFatalError(BaseFatalError):
    """A policy denies access to a delegate, coder, filter, path, or
       resource."""
    wand_error_code = ...


TYPE_MAP = ...
