"""
This type stub file was generated by pyright.
"""

import ctypes

""":mod:`wand.cdefs.structures` --- MagickWand C typedefs
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.. versionadded:: 0.5.0
"""
__all__ = ('c_magick_real_t', 'c_magick_size_t', 'c_ssize_t')
if not hasattr(ctypes, 'c_ssize_t'):
    ...
c_ssize_t = ctypes.c_ssize_t
env_real = ...
if env_real in ('double', 'c_double'):
    c_magick_real_t = ...
else:
    c_magick_real_t = ...
if ctypes.sizeof(ctypes.c_size_t) == 8:
    c_magick_size_t = ...
else:
    c_magick_size_t = ...
    c_magick_size_t = ...
